name: Saluations CI

on:
  push:
    branches:
      - 'feature/refacto'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: test and buid
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: |
         npm ci
         npm run build --if-present
         npm run lint
         npm test
         npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          path: ./dist

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1