name: Saluations CI

on:
  push:
    branches:
      - 'feature/refacto'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: test and buid
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: |
         npm ci
         npm run build --if-present
         npm run lint
         npm test
         npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: github-pages
          path: ./dist

  deploy:
    # Add a dependency to the build job
    needs: build

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1